services:
  consul:
    image: hashicorp/consul:1.21.4
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"

  ui-service:
    build:
      context: ./ui-service
    container_name: ui-service
    depends_on:
      - consul
    ports:
      - "8080:8080"