pipeline {
    agent any

    stages {
        stage('build jar') {
            steps {
                powershell '''
                Set-Location "F:\\Work\\Projects\\IdeaProjects\\bank-app-yandex-practicum-sprint-9"
                .\\mvnw.cmd clean package
                '''
            }
        }

        stage('switch context') {
            steps {
        powershell '''
        $dockerEnv = minikube -p minikube docker-env --shell powershell
        $dockerEnv | Where-Object { $_ -match '=' } | ForEach-Object { Invoke-Expression $_ }
        '''
            }
        }

        stage('build docker') {
            steps {
                powershell '''
                docker build -t cash-service:1.0 .\\cash-service
                '''
            }
        }

        stage('deploy') {
            steps {
                powershell '''
                helm install cash-service ./bank-app/charts/cash-service
                '''
            }
        }
    }
}
