spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    consul:
      host: consul
      port: 8500
    config:
      server:
        native:
          search-locations: classpath:/configurations/

server:
  port: 8080